name: Deploy manual (plugged) to B2 Cloud

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: plugged
        fetch-depth: 1

    - name: Deploy to B2 Cloud
      uses: GamemakerChina/backblaze-b2-action@main
      env:
        SOURCE_DIR: './'
        B2_BUCKET: ${{ secrets.B2_BUCKET_PLUGGED }}
        B2_APPKEY_ID: ${{ secrets.B2_APPKEY_ID_PLUGGED }}
        B2_APPKEY: ${{ secrets.B2_APPKEY_PLUGGED }}
        B2_SYNC_THREADS: 1