name: Build manual with plugged method (Windows)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Prepare submodules
      run: |
        git submodule update --init --remote GMS2-Robohelp-en/

    - name: Copy build files
      run: xcopy .\GMS2-Robohelp-en .\build /E /H /C /I

    - name: Run build executable files
      run: .\GameMakerManualTranslatorBuild.exe
    
    - name: Upload Artifacts
      uses: actions/upload-artifact@v1
        with:
          name: manual
          path: build
  # https://github.com/JamesIves/github-pages-deploy-action#operating-system-support-
  deploy:
    concurrency: ci-${{ github.ref }}
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download Artifacts
        uses: actions/download-artifact@v1
        with:
          name: manual

      - name: Deploy to plugged branch
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          branch: plugged
          folder: 'manual'
