name: Build manual with plugged method (Linux)

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Prepare submodules
      run: |
        git submodule update --init --remote GMS2-Robohelp-en/
        git submodule update --init --remote GameMakerManualExport/

    - name: Set Node.js version to 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Set Python version to 3.10.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Use pnpm instead npm
      run: npm install -g pnpm

    - name: Prepare environments
      run: |
        cd GameMakerManualExport
        pnpm install
        pnpm run init:build

    - name: Import translations to manual
      run: |
        cd GameMakerManualExport
        pnpm run plugged:gendep
        pnpm run plugged:import
        pnpm run plugged:team

    - name: Clean temp files
      run: |
        cd GameMakerManualExport
        pnpm run clean:temp
        cd ..

    - name: Deploy to plugged branch
      uses: JamesIves/github-pages-deploy-action@releases/v4
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        branch: plugged
        folder: build
