name: Build manual with plugged method (Windows)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Prepare submodules
      run: |
        git submodule update --init --remote GMS2-Robohelp-en/

    - name: Copy build files
      run: xcopy .\GMS2-Robohelp-en .\build /E /H /C /I

    - name: Run build executable files
      run: .\GameMakerManualTranslatorBuild.exe

    - name: Deploy to plugged branch
      uses: JamesIves/github-pages-deploy-action@releases/v4
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        branch: plugged
        folder: build
