name: Build manual with static method

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Prepare submodules
      run: |
        git submodule update --init --remote GMS2-Robohelp-en/
        git submodule update --init --remote GameMakerManualExport/

    - name: Use pnpm instead npm
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - run: npm install -g pnpm

    - name: Prepare environments
      run: |
        cd GameMakerManualExport
        pnpm install
        pnpm run init:build

    - name: Import translations to manual
      run: |
        cd GameMakerManualExport
        pnpm run static:gendep
        pnpm run static:import
        pnpm run static:team

    - name: Clean temp files
      run: |
        cd GameMakerManualExport
        pnpm run clean:temp
        cd ..

    - name: Deploy to static branch
      uses: JamesIves/github-pages-deploy-action@releases/v4
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        branch: static
        folder: build

    - name: Deploy to B2 Cloud
      uses: getpersio/backblaze-b2-action@main
      env:
        SOURCE_DIR: './build'
        B2_BUCKET: ${{ secrets.B2_BUCKET_STATIC }}
        B2_APPKEY_ID: ${{ secrets.B2_APPKEY_ID_STATIC }}
        B2_APPKEY: ${{ secrets.B2_APPKEY_STATIC }}
        B2_SYNC_THREADS: 1
    